ONLINE_STORE/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages_app.urls", namespace="pages")),
    
    path("users/", include("users_app.urls", namespace="users")),
    path("products/", include("products_app.urls", namespace="products")),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages_app/urls.py
from django.urls import path
from . import views


app_name = "pages"


urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    
]

products_app/urls.py
from django.urls import path
from . import views


app_name = "products"


urlpatterns = [
    path("cart/", views.CartPageView.as_view(), name="cart"),
    # path("add_to_cart/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("change_cart_quantity/", views.change_cart_quantity, name="change_cart_quantity"),
    path("set_cart_quantity", views.set_cart_quantity, name="set_cart_quantity"),
    path("categories/", views.CategoriesPageView.as_view(), name="categories"),
    path("", views.ProductsPageView.as_view(), name="products"),
    path("<int:pk>/", views.ProductDetailPageView.as_view(), name="product_detail"),
]

users_app/urls.py
from django.urls import path
from . import views


app_name = "users"


urlpatterns = [
    path("register/", views.RegisterPageView.as_view(), name="register"),
    path("login/", views.login_view, name="login"),
    path("account/", views.AccountPageView.as_view(), name="account"),
    path("account_update/<int:pk>/", views.AccountUpdateView.as_view(), name="account_update"),
    path("logout/", views.logout_view, name="logout")
]

templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- Font Awesome -->
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
			rel="stylesheet"
		/>
		<!-- Google Fonts -->
		<link
			href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
			rel="stylesheet"
		/>
		<!-- <link 
		href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
		rel="stylesheet" 
		integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
		crossorigin="anonymous"> -->
		<!-- MDB -->
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.min.css"
			rel="stylesheet"
		/>
		<!-- Option 1: Include in HTML -->
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
		/>
		<title>Online Store | Account</title>
	</head>
    <body>

        {% include 'layouts/header.html' %}

        {% block content %}
        {% endblock content %}
<!-- 
        <script
			type="text/javascript"
			src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.umd.min.js"
		></script> -->

    </body>
</html>

templates/layouts/header.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Online Store</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'products:categories' %}">
                        <i class="bi bi-layers-fill"></i>
                        Categories
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a
                            class="nav-link active d-flex align-items-center gap-1"
                            aria-current="page"
                            href="{% url 'users:account' %}"
                        >
                            <i class="bi bi-person"></i>

                            Account
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            class="nav-link d-flex align-items-center gap-1"
                            aria-current="page"
                            href="{% url 'products:cart' %}"
                        >
                            <i class="bi bi-cart4"></i>
                            My Cart
                        </a>
                    </li>
                {% endif %}
            </ul>
            <div class="d-flex align-items-center gap-2">
                <form action="{% url 'products:products' %}" method="get" class="d-flex" role="search">
                    <input
                        class="form-control me-2"
                        type="search"
                        placeholder="Search"
                        aria-label="Search"
                        name="search"
                    />
                    <button class="btn btn-outline-light" type="submit">
                        Search
                    </button>
                </form>
                {% if request.user.is_authenticated %}
                    <a class="btn btn-outline-light" href="{% url 'users:logout' %}">logout</a>
                {% else %}
                    <a class="btn btn-outline-light" href="{% url 'users:login' %}">signin/signup</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>