ONLINE_STORE/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages_app.urls", namespace="pages")),
    
    path("users/", include("users_app.urls", namespace="users")),
    path("products/", include("products_app.urls", namespace="products")),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages_app/urls.py
from django.urls import path
from . import views


app_name = "pages"


urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    
]

products_app/urls.py
from django.urls import path
from . import views


app_name = "products"


urlpatterns = [
    path("cart/", views.CartPageView.as_view(), name="cart"),
    # path("add_to_cart/", views.AddToCartView.as_view(), name="add_to_cart"),
    path("change_cart_quantity/", views.change_cart_quantity, name="change_cart_quantity"),
    path("set_cart_quantity", views.set_cart_quantity, name="set_cart_quantity"),
    path("categories/", views.CategoriesPageView.as_view(), name="categories"),
    path("", views.ProductsPageView.as_view(), name="products"),
    path("<int:pk>/", views.ProductDetailPageView.as_view(), name="product_detail"),
]

users_app/urls.py
from django.urls import path
from . import views


app_name = "users"


urlpatterns = [
    path("register/", views.RegisterPageView.as_view(), name="register"),
    path("login/", views.login_view, name="login"),
    path("account/", views.AccountPageView.as_view(), name="account"),
    path("account_update/<int:pk>/", views.AccountUpdateView.as_view(), name="account_update"),
    path("logout/", views.logout_view, name="logout")
]

templates/account.html
{% extends 'layouts/base.html' %}


{% block content %}

<main class="vh-100 bg-body-tertiary">
	<div class="container m-auto mt-5 row gap-2 justify-content-center">
		<h1 class="d-flex justify-content-center mb-5">Your account</h1>
		<div class="d-flex justify-content-center gap-5">
			<img
				style="max-width: 300px; max-height: 100%; border-radius: 50%"
				src="https://cdn3.iconfinder.com/data/icons/player/128/sound-18-1024.png"
				alt=""
			/>
			<div class="w-50">
				<form action="{% url 'users:account_update' pk=request.user.pk %}" method="post">
					<div class="d-flex flex-column gap-2">
						{% csrf_token %}

						{% for field in form %}
							<div data-mdb-input-init class="form-outline mb-4">
								<label 
								class="text-dark form-label" 
								for="form{{ forloop.counter }}Example13"
								>{{ field.label }}</label>

								<input 
								type="{{ field.widget.attrs.type }}" 
								name="{{ field.name }}" 
								value="{{ field.value|default:'' }}"
								class="w-100">

							</div>
						{% endfor %}
						
						<button class="btn btn-dark" type="submit">
							Update  information
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</main>

{% endblock content %}

templates/cart.html
{% extends 'layouts/base.html' %}


{% block content %}

<main class="vh-100 bg-body-tertiary">
	<div class="container m-auto mt-5 row gap-2 justify-content-center">
		<h1 class="d-flex justify-content-center">Checkout</h1>
		<section class="h-100 gradient-custom">
			<div class="container py-2">
				<div class="row d-flex justify-content-center my-4">
					<div class="col-md-8">
						<div class="card mb-4">
							<div class="card-header py-3">
								<h5 class="mb-0">Cart - {{ objects.count }} items</h5>
							</div>
							<div class="card-body">
								{% for object in objects %}
									<div class="row">
										<div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
											<div
												class="bg-image hover-overlay hover-zoom ripple rounded"
												data-mdb-ripple-color="light"
											>
												<img
													src="{{ object.product.image.url }}"
													class="w-100"
													alt="Blue Jeans Jacket"
												/>
												<a href="{% url 'products:product_detail' pk=object.product.pk %}">
													<div
														class="mask"
														style="background-color: rgba(251, 251, 251, 0.2)"
													></div>
												</a>
											</div>
										</div>

										<div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
											<!-- Data -->
											<p><strong>{{ object.product.name }}</strong></p>
											<p>{{ object.product.description }}</p>
											<form action="{% url 'products:change_cart_quantity' %}" method="post">
												{% csrf_token %}
												<input type="hidden" name="product_id" value="{{ object.product.id }}">
												<input type="hidden" name="quantity" value="-{{ object.quantity }}">
												<button
													type="submit"
													data-mdb-button-init
													data-mdb-ripple-init
													class="btn btn-primary btn-sm me-1 mb-2"
													data-mdb-tooltip-init
													title="Remove item"
												>
													<i class="fas fa-trash"></i>
												</button>
											</form>
											
											
											
										</div>

										<form action="{% url 'products:set_cart_quantity' %}" method="post" class="col-lg-4 col-md-6 mb-4 mb-lg-0">
											{% csrf_token %}
											<input type="hidden" name="product_id" value="{{ object.product.pk }}">
											<input type="hidden" name="next" value="{{ request.path }}">
											
											<div class="d-flex mb-4" style="max-width: 300px">
												<button
													id="btn"
													data-mdb-button-init
													data-mdb-ripple-init
													type="button"
													class="btn btn-primary px-3 me-2 minus">
													<i class="fas fa-minus"></i>
												</button>

												<div data-mdb-input-init class="form-outline">
													<input
														id="form1"
														min="0"
														name="quantity"
														value="1"
														type="number"
														class="form-control"
													/>
													<label class="form-label" for="form1"
														>Quantity</label
													>
												</div>

												<button
													id="btn"
													data-mdb-button-init
													data-mdb-ripple-init
													type="button"
													class="btn btn-primary px-3 ms-2 plus">
													<i class="fas fa-plus"></i>
												</button>
											</div>
											
											<p class="text-start text-md-center">
												<strong>$17.99</strong>
											</p>
										
										</form>
									</div>

									<hr class="my-4" />
								{% endfor %}
							</div>
						</div>
						<div class="card mb-4">
							<div class="card-body">
								<p><strong>Expected shipping delivery</strong></p>
								<p class="mb-0">12.10.2020 - 14.10.2020</p>
							</div>
						</div>
						<div class="card mb-4 mb-lg-0">
							<div class="card-body">
								<p><strong>We accept</strong></p>
								<img
									class="me-2"
									width="45px"
									src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
									alt="Visa"
								/>
								<img
									class="me-2"
									width="45px"
									src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
									alt="American Express"
								/>
								<img
									class="me-2"
									width="45px"
									src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
									alt="Mastercard"
								/>
								<img
									class="me-2"
									width="45px"
									src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
									alt="PayPal acceptance mark"
								/>
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="card mb-4">
							<div class="card-header py-3">
								<h5 class="mb-0">Summary</h5>
							</div>
							<div class="card-body">
								<ul class="list-group list-group-flush">
									<li
										class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0"
									>
										Products
										<span>${{ total_price }}</span>
									</li>
									<li
										class="list-group-item d-flex justify-content-between align-items-center px-0"
									>
										Shipping
										<span>Gratis</span>
									</li>
									<li
										class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3"
									>
										<div>
											<strong>Total issue</strong>
											<strong>
												<p class="mb-0">(including VAT)</p>
											</strong>
										</div>
										<span><strong>${{ total_amount }}</strong></span>
									</li>
								</ul>

								<button
									type="button"
									data-mdb-button-init
									data-mdb-ripple-init
									class="btn btn-primary btn-lg btn-block"
								>
									Go to checkout
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</main>

<script>

	const btns = document.querySelectorAll("#btn");

	btn_handle = (btn, number) => {
		btn.addEventListener("click", e => {
			e.preventDefault()
			
			const btnForm = btn.parentNode.parentNode

			const input = btnForm.querySelector("input[type=number]");
			input.value -= -number

			btnForm.submit()
		})
	} 

	minus_func = btn => btn_handle(btn, -1)
	plus_func = btn => btn_handle(btn, 1)

	const function_for = {
		"minus": minus_func,
		"plus": plus_func
	}

	btns.forEach(
		btn => {
			const splited_id = btn.className.split(" ")
			
			if (splited_id.length < 2) {
				console.error("id of Btn:", btn, "is invalid")
				return;
			}

			const pl_mi = splited_id.find(element => element === "plus" || element === "minus");
			
			if (!pl_mi) {
				console.error("Bad btn")
				return;
			}

			function_for[pl_mi](btn)

		}
	)

</script>

{% endblock content %}

templates/categories.html
{% extends 'layouts/base.html' %}


{% block content %}

<main class="">
	<div class="container m-auto mt-5 row gap-2 justify-content-center">
		{% for object in objects %}
			<div class="card col-3 p-0">
				<img
					class="card-img-top"
					src="{{ object.image.url }}"
					alt="Card image cap"
				/>
				<div class="card-body">
					<h3>
						<a class="text-decoration-none" href="{% url 'products:products' %}?category={{ object.name }}"
							>{{ object.name }}</a
						>
					</h3>
					<p class="card-text">
						{{ object.description }}
					</p>
					<div class="d-flex flex-column gap-2"></div>
				</div>
			</div>

		{% empty %}
			
			<h1>There are no categories</h1>

		{% endfor %}

	</div>

	<div class="d-flex justify-content-center mt-5">
		{% include 'components/pagination.html' %}
	</div>
</main>

{% endblock content %}

templates/detail.html
{% extends 'layouts/base.html' %}


{% block content %}

    <main class="d-flex justify-content-center gap-5 m-auto" style="height: 100dvh; width: 100vw;">

        <div class="w-25 h-100 d-flex justify-content-start align-items-start mt-5">
            <img
            style="max-width: 100%; max-height: 100%;" 
            src="{{ product.image.url }}" 
            alt="Product Image" >
        </div>

        <div class="w-50  mt-5">

            <h1 style="font-size: 3.5rem;">{{ product.name }}</h1>
            <p class="d-flex justify-content-start align-items-start flex-wrap h-3 fs-4">
                {{ product.description }}
            </p>

            <form 
            id="product-form"
            class="d-flex justify-content-center align-items-center gap-1 flex-column"
            style="width: max-content;"
            action="{% url 'products:change_cart_quantity' %}" 
            method="post">
            {% csrf_token %}
                <div class="flex-nowrap d-flex justify-content-center align-items-center gap-1">
                    <input type="hidden" id="form-input" name="quantity" value="{{ product_quantity }}">
                    <input type="hidden" name="product_id", value="{{ product.pk }}">
                    <input type="button" class="form-btn btn btn-success fs-3" value="-">
                    <p id="form-input-shadow"
                    class="d-flex justify-content-center align-items-center fs-3 p-2 text-white"
                    style="width: 4rem; height: 120%; background-color: grey; margin-bottom: 0;">{{ product_quantity }}</p>

                    <input type="button" class="form-btn btn btn-success fs-3" value="+">
                </div>
                <button 
                class="w-100 btn-primary btn" 
                type="submit"
                >Add to cart</button>
            </form>

        </div>

    </main>

    <script>
        const startInputVal = Number(getInput().value)
        
        const form = document.getElementById("product-form")

        form.addEventListener("submit", e => {
            e.preventDefault()
            
            const distance = Number(getInput().value) - startInputVal
            
            const input = getInput()
            input.value = distance
            
            form.submit()

        })


        function getInput() {
            const input = document.getElementById("form-input");
            return input
        }

        function reRender(val) {
            const rendererTag = document.getElementById("form-input-shadow")
            rendererTag.innerHTML = val
        }

        function addToInputValue(val) {
            const input = getInput()
            input.value -= -Number(val)
            input.value = Number(input.value)
            
            reRender(input.value)
        }

        buttons = document.querySelectorAll(".form-btn");

        buttons.forEach(element => {
            element.addEventListener("click", e => {
                e.preventDefault()
                const changer = e.target.value === "-" ? -1 : 1
                
                const input = getInput()

                if (input.value - -changer > -1) {
                    addToInputValue(changer)
                }
            })
        });

    </script>

{% endblock content %}

templates/login.html
{% extends 'layouts/base.html' %}

{% block content %}

<section class="vh-100 bg-dark">
	<div class="container py-5 h-100">
		<div class="row d-flex align-items-center justify-content-center h-100">
			<div class="col-md-8 col-lg-7 col-xl-6">
				<img
					src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
					class="img-fluid"
					alt="Phone image"
				/>
			</div>
			<div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
				<form action="" method="post">
					{% csrf_token %}

					{% for field in form %}
						<div data-mdb-input-init class="form-outline mb-4">
							{{ field }}
							<label 
							class="text-light " 
							for="form{{ forloop.counter }}Example13"
							>{{ field.label }}</label>

						</div>
					{% endfor %}

					<button
						type="submit"
						data-mdb-button-init
						data-mdb-ripple-init
						class="btn btn-primary btn-lg btn-block"
					>
						Sign up
					</button>

					<div
						class="divider d-flex align-items-center my-4 d-flex justify-content-center"
					>
						<p class="text-light text-center fw-bold mx-3 mb-0">OR</p>
					</div>

					{% load socialaccount %}
					{% get_providers as social_providers %}
					{% for provider in social_providers %}

						<a
							data-mdb-ripple-init
							class="btn btn-primary btn-lg btn-block text-primary"
							style="background-color: #ffffff"
							href="{% provider_login_url provider.id %}"
							role="button"
						>
							<i class="fab fa-google me-2 text-primary"></i>Continue with {{ provider.name }}
						</a>
					{% endfor %}
				</form>
				<div class="d-flex justify-content-center mt-3">
					<p class="m-0 text-light">
						Don't have an account ?
						<a href="{% url 'users:register' %}">Sign up</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock content %}

templates/products.html
{% extends 'layouts/base.html' %}


{% block content %}

<main class="vh-100 bg-body-tertiary">
	<div class="container m-auto mt-5 row gap-2 justify-content-center">
		<h1 class="d-flex justify-content-center mb-10">{{ category }}</h1>
		{% for object in objects %}
			<div class="card col-3 p-0">
				<img
					class="card-img-top"
					src="{{ object.image.url }}"
					alt="Card image cap"
				/>
				<div class="card-body">
					<h3>
						<a class="text-decoration-none" href="{% url 'products:product_detail' pk=object.pk %}">{{ object.name }}</a>
					</h3>
					<p class="card-text">
						{{ object.description }}
					</p>
					<div class="d-flex flex-column gap-2">
						{% if object.last_price %}
						<div class="d-flex align-items-center gap-2">
							<b>
								<small> Old price: </small>
							</b>
							<small class="text-decoration-line-through">
								<b class="text-danger">${{ object.last_price }}</b>
							</small>
						</div>
						{% endif %}
						<div class="d-flex align-items-center gap-2">
							<b>
								<small>Current price: </small>
							</b>
							<small class="">
								<b class="text-success">${{ object.current_price }}</b>
							</small>
						</div>
					</div>
					<form action="{% url 'products:change_cart_quantity' %}" method="post">
						{% csrf_token %}
						<input type="hidden" name="product_id" value="{{ object.pk }}">
						<input type="hidden" name="quantity" value="1">
						<button
						type="submit"
						class="mt-2 w-100 d-flex align-items-center justify-content-center font-bold btn btn-warning"
					>
						<i class="bi bi-cart-plus"></i>
						Add to cart
					</button>
					</form>
					
				</div>
			</div>
		{% empty %}
			<h1>There is not Products</h1>
		{% endfor %}
	</div>
	<div class="d-flex justify-content-center mt-5">
		<nav aria-label="...">
			{% include 'components/pagination.html' %}
		</nav>
	</div>
</main>

{% endblock content %}

templates/registration.html
{% extends 'layouts/base.html' %}


{% block content %}

<section class="vh-100 bg-dark">
	<div class="container py-5 h-100">
		<div class="row d-flex align-items-center justify-content-center h-100">
			<div class="col-md-8 col-lg-7 col-xl-6">
				<img
					src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
					class="img-fluid"
					alt="Phone image"
				/>
			</div>
			<div class="col-md-7 col-lg-5 col-xl-5 offset-l-1">
				<form action="" method="post">
					{% csrf_token %}
					{% for field in form %}
						<div data-mdb-input-init class="form-outline mb-4">
							{{ field }}
							<label 
							class="text-light form-label" 
							for="form{{ forloop.counter }}Example13"
							>{{ field.label }}</label>

						</div>
					{% endfor %}

					<button
						type="submit"
						data-mdb-button-init
						data-mdb-ripple-init
						class="btn btn-primary btn-lg btn-block"
					>
						Sign up
					</button>

					<div
						class="divider d-flex align-items-center my-4 d-flex justify-content-center"
					>
						<p class="text-light text-center fw-bold mx-3 mb-0">OR</p>
					</div>
					{% load socialaccount %}
					
						<a
							data-mdb-ripple-init
							class="btn btn-primary btn-lg btn-block text-primary"
							style="background-color: #ffffff"
							href="{% url 'account_signup' %}"
							role="button"
						>
							<i class="fab fa-google me-2"></i>Continue with Providers
						</a>
					
				</form>
				<div class="d-flex justify-content-center mt-3">
					<p class="m-0 text-light">
						Already have an account ?
						<a href="{% url 'users:login' %}">Sign in</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock content %}